# Generated by Django 5.0.2 on 2024-02-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AvailableSite",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("domain", models.CharField(max_length=200)),
                ("atrributes", models.CharField(max_length=200)),
                ("theme", models.CharField(max_length=200)),
                ("base_template", models.CharField(max_length=200)),
                ("desctiption", models.CharField(max_length=200)),
                ("author", models.CharField(max_length=200)),
            ],
        ),
    ]
